name: Tag Scan with Trivy

on:
  create:
    tags:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Run Trivy Scan
        id: trivy_scan
        run: |
          # Run Trivy scan on the specified directory or file
          trivy fs --exit-code 1 --severity HIGH,CRITICAL . || echo "Trivy scan failed, exiting with non-zero status."

      - name: Create Tag
        if: success() && github.event.ref_type == 'tag'
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Create the tag
          git tag $TAG_NAME
          git push origin $TAG_NAME
