name: Tag Scan with Trivy

on:
  create:
    tags:
      - '*'

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy Scan
        id: trivy_scan
        uses: aquasecurity/trivy-action@v0.4.0
        with:
          scan-type: 'fs'  # Change to 'image' if scanning a Docker image
          severity: 'HIGH,CRITICAL'
          exit-code: '1'  # Exit with code 1 if vulnerabilities are found
          path: '.'  # Path to scan; adjust as necessary

      - name: Create Tag
        if: success() && github.event.ref_type == 'tag'
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          
          # Create the tag
          git tag $TAG_NAME
          git push origin $TAG_NAME
